name: geofencing
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.2
  http: ^0.13.4
  flutter_markdown: ^0.6.9
  cupertino_icons: ^1.0.2
  flutter_map_location: any
  localstorage: ^4.0.0+1
  sqflite: ^2.0.2
  qr_code_scanner: ^0.7.0
  flutter_local_notifications: ^9.3.2
  flutter_geofence: ^0.4.2
  poly_geofence_service: ^1.5.8
  connectivity_plus: ^2.2.1
  shared_preferences: ^2.0.13
  vibration: ^1.7.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  assets:
    - assets/logo.png
    - assets/config/config.json
  uses-material-design: true